### ISSUE TITLE
rekordcrate-pdb - Error: no variants matched at 0x307f

### ISSUE THREAD

**Issue by davidhaley** [Holzhaus/rekordcrate#72]
![out](https://user-images.githubusercontent.com/11729897/167312089-53499db3-06b1-4012-8673-87184c825ef1.png)

**Comment by Swiftb0y** [comment]
Thanks for your bug report. Can you also send us the `.pdb` this issue occurred with so we can properly look into it? Thanks

**Comment by Holzhaus** [comment]
Yup, thanks for testing! As @Swiftb0y pointed out, we need the PDB file to debug the issue. If you don't want to share it publicly (e. g. because listening to "Crazy Frog" is your guilty pleasure and you don't want anyone to know), you can also send us the PDB file privately. Just say so here and we will figure something out.

**Comment by davidhaley** [comment]
> because listening to "Crazy Frog" is your guilty pleasure and you don't want anyone to know

lol!

Hey guys, sorry for the delay - Jan, I just sent you an email with the file.

Thank you!

**Comment by Holzhaus** [comment]
Thanks. Looks like the color index of a track is out of range. If I add a workaround for that, the string section of track rows fail to parse, so this needs some more investigation.

@davidhaley What rekordbox version this this file created with? (You can check with `cargo run --bin rekordcrate-setting -- /path/to/PIONEER/DEVSETTING.DAT`)
Does it work fine on a CDJ? (just to rule out that the file got corrupted).

**Comment by Swiftb0y** [comment]
@davidhaley would you mind if Jan shared the file with me as well so I can also take a look?

**Comment by davidhaley** [comment]
Thank you.

> What rekordbox version this this file created with?

Please see below:

![out](https://user-images.githubusercontent.com/11729897/167848200-d8e4e60c-7c46-4564-8216-01c7caa73b63.png)

> Does it work fine on a CDJ? (just to rule out that the file got corrupted).

Yes, the USB loads and plays fine on both a CDJ-3000 and CDJ-2000NXS2.

> would you mind if Jan shared the file with me as well so I can also take a look?

I don't mind @Swiftb0y, thank you for asking.

**Comment by Swiftb0y** [comment]
Thank you very much. We'll get back to you once we have investigated the issue.

**Comment by Holzhaus** [comment]
@davidhaley the issue is fixed on latest main. Thanks for providing the PDB file.
